name: tag release

on:
  push:
    branches:
      - main
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Create Version"
        id: version_cfg
        # note: Go lang requires tag format: v0.12.3-4
        # see: https://stackoverflow.com/questions/62140832/why-golang-packages-have-to-be-v0-or-v1-and-not-v2020
        run: |-
          VER_BUILD=$(date +%H%M)
          VERSION_NUM="0.$(date +%y)$(date +%m).$(date +%d)-${VER_BUILD:0:3}"
          echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT

      - name: "Tag release"
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_cfg.outputs.VERSION_NUM }}
          release_name: v${{ steps.version_cfg.outputs.VERSION_NUM }}
          draft: false
          prerelease: false
