name: "Create version tag"

on: [workflow_dispatch]

jobs:
  tag-branch:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v4

      - name: "Create Version Tag"
        id: version_cfg
        # note: Go lang requires tag format: v0.12.3-4
        # see: https://stackoverflow.com/questions/62140832/why-golang-packages-have-to-be-v0-or-v1-and-not-v2020
        run: |-
          VER_BUILD=$(date +%H%M)
          # limit to only first 3 chars
          VER_BUILD=${VER_BUILD:0:3}
          # 'strict' semver segments cannot start with 0
          VERSION_NUM="0.$(date +%y)$(date +%m).$(date +%-d).${VER_BUILD#0}"
          echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT
          # recreate as INT, leaving 0's in place; creates a 'reasonable' 32-bit signed int.
          VERSION_INT="$(date +%y)$(date +%m)$(date +%d)${VER_BUILD}"
          echo "VERSION_INT=${VERSION_INT}" >> $GITHUB_OUTPUT

      - name: "Tag branch"
        run: |-
          TAG2USE=v${{ steps.version_cfg.outputs.VERSION_NUM }}
          git tag ${TAG2USE}
          git push origin ${TAG2USE}
          echo "::notice::Pushed tag ${TAG2USE} to repo branch ${{ env.GITHUB_REF }}"
